# Generated by Django 6.0.1 on 2026-01-29 01:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_equipamento_especificacoes_equipamento_foto_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estoquetecnico',
            options={'verbose_name': 'Carteira do Técnico (Saldo)', 'verbose_name_plural': 'Carteiras dos Técnicos (Saldos)'},
        ),
        migrations.AlterModelOptions(
            name='movimentacao',
            options={'verbose_name': 'Registrar Movimentação', 'verbose_name_plural': 'Registrar Movimentações'},
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='tipo',
            field=models.CharField(choices=[('FIBRA', 'Fibra Óptica'), ('RADIO', 'Via Rádio'), ('FERRAMENTA', 'Ferramentas'), ('TORRES', 'Equipamento para Torres')], max_length=20),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='autor_movimento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autor_log', to=settings.AUTH_USER_MODEL, verbose_name='Quem registrou'),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='tipo',
            field=models.CharField(choices=[('SAIDA', '🔴 Retirada (Sai do Estoque -> Vai pro Técnico)'), ('DEVOLUCAO', '🟢 Devolução (Sai do Técnico -> Volta pro Estoque)'), ('BAIXA', '✅ Baixa em OS (Sai do Técnico -> Cliente/Lixo)')], max_length=20),
        ),
    ]
